### ISSUE TITLE
Add links to WCAG

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#1]
In the intro where it says WCAG 2.0 replace it with WCAG 2.0 and WCAG 2.1 and make them into anchor tags.

WCAG 2.0 should link to criteria 1.4.3 https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

WCAG 2.1 should link to criteria 1.4.6 https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html

**Comment by Dhruv-Gajjar** [comment]
I would like to work on this issue.

**Comment by EmmaDawsonDev** [comment]
Great! Let me know if you have any questions

**Comment by Dhruv-Gajjar** [comment]
Yea..I wanted to know whether the link should open on a new page or on the same page?.

**Comment by EmmaDawsonDev** [comment]
They can open in the same page

**Comment by EmmaDawsonDev** [comment]
Closed by https://github.com/AccessibleForAll/ColorPaletteCombos/commit/7a94e808a425276ff58b0d36af511ada6565aa7b
