### ISSUE TITLE
Add support for RGB

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#17]
Currently the site only accepts inputs in the form of hex codes.

It would be great to accept rgb color format too.

**Comment by Hat52** [comment]
I would like to work on it

**Comment by EmmaDawsonDev** [comment]
Before you start, someone mentioned that the input type=color has this functionality built in but it might not be fully accessible so I need a couple of days in order to test it out. I'll get back to you if this issue still needs working on

**Comment by Hat52** [comment]
Sure

**Comment by EmmaDawsonDev** [comment]
I think we can sort this by adding the color picker as suggested in #16 so I'll close this for now. I'll reopen it if we can't get it to work with the color picker
