### ISSUE TITLE
Separate css into modules for each component

### ISSUE THREAD

**Issue by timo-tech19** [AccessibleForAll/ColorPaletteCombos#18]
**Is your feature request related to a problem? Please describe.**
App.css file is too large

**Describe the solution you'd like**
Separate CSS code into CSS module files for each specific component

**Describe alternatives you've considered**
I'm also thinking of changing the component folder structure such that each component has a separate folder with its .jsx and CSS files

**Comment by EmmaDawsonDev** [comment]
This sounds great, Timo. I’ll assign it to you but please let me know as soon as you need any help.

**Comment by timo-tech19** [comment]
great!

**Comment by EmmaDawsonDev** [comment]
Fixed by #21
