### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#2]
The footer should contain:
- A link to the repository
- A 'Report a bug' link to create a new issue

**Comment by murtuzaalisurti** [comment]
Can I work on this issue?

**Comment by EmmaDawsonDev** [comment]
Sure! Please go ahead. Any questions please let me know

**Comment by murtuzaalisurti** [comment]
![screenshot of footer](https://user-images.githubusercontent.com/68743212/176937879-c0907b3f-61c3-423b-bd25-b788c8309135.jpg)

@emmalearnscode should I add more styling or you want it simple?

**Comment by EmmaDawsonDev** [comment]
That looks great for now 😀

**Comment by EmmaDawsonDev** [comment]
Closed by #12
