### ISSUE TITLE
[DOCS] - Update documentation

### ISSUE THREAD

**Issue by frankiefab100** [AccessibleForAll/ColorPaletteCombos#20]
The `README` should explain how to use the Color Palette Combos, and other details (like the license, code of conduct, etc)

**Comment by EmmaDawsonDev** [comment]
Instructions would be great. There’s already a link to the license but a link to the code of conduct could be added.

**Comment by frankiefab100** [comment]
Alright, do you have any note as the instruction manual yet?

**Comment by PratishShrivastava** [comment]
Please Assign me to this issue

**Comment by namn-grg** [comment]
Hello Emma!
Can I work on this one? 
I'll add the instructions and necessary links.
Thank you!

**Comment by EmmaDawsonDev** [comment]
Sure @naman-ng

**Comment by hariscs** [comment]
hey @EmmaDawsonDev i can work on this

**Comment by EmmaDawsonDev** [comment]
Sure, go ahead

**Comment by hariscs** [comment]
this issue should be closed, my PR for this issue already got merged.
