### ISSUE TITLE
Add gitpod badge to readme

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#27]
Please add the following code snippet to the bottom of the readme file 

```[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/AccessibleForAll/ColorPaletteCombos)```

**Comment by krupalitrivedi** [comment]
Hi Emma!

Can I work on this one? :)

It is okay if this is for someone else!
Thank you!

**Comment by EmmaDawsonDev** [comment]
Go for it :)
