### ISSUE TITLE
Add explanation of Gitpod to readme

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#29]
Between the gitpod heading and the gitpod button add the following sentence to explain what Gitpod is:

Gitpod allows you to view and interact with this code directly in the browser without the need to clone it to your local machine. If you wish to make changes that lead to a pull request, remember to fork the repository then click the Gitpod button in the forked readme. Otherwise, feel free to play around with the code by clicking here.

**Comment by Viki-07** [comment]
Hey @EmmaDawsonDev, It seems interesting and I would like to work on this and It will be very helpful for me as I am participating in Hacktoberfest. Kindly assign me for the above

**Comment by EmmaDawsonDev** [comment]
Sure!
