### ISSUE TITLE
Docs: add screenshot

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#3]
Add a screenshot of the site to the readme

**Comment by nawed2611** [comment]
Can I solve this issue?

**Comment by EmmaDawsonDev** [comment]
Sure!

**Comment by EmmaDawsonDev** [comment]
The site is now hosted here https://colorpalettecombos.netlify.app/ which should make it easier for you to add a screenshot 😄 Feel free to add a few extra colors to show that it can compare more than 2 colors at once

**Comment by ayushv45** [comment]
Can I solve this issue ?

**Comment by nawed2611** [comment]
> The site is now hosted here https://colorpalettecombos.netlify.app/ which should make it easier for you to add a screenshot 😄 Feel free to add a few extra colors to show that it can compare more than 2 colors at once

thankss that would help!

**Comment by nawed2611** [comment]
Will this work?

<img width="670" alt="image" src="https://user-images.githubusercontent.com/83456083/176761468-2291df3a-6014-4e60-8f0c-9ebd348fd8f4.png">

**Comment by EmmaDawsonDev** [comment]
Yes, that looks great!

**Comment by EmmaDawsonDev** [comment]
Closed by https://github.com/AccessibleForAll/ColorPaletteCombos/commit/277dca3498f36cc4036a7485385a8f3ca0cccd7f
