### ISSUE TITLE
Add a way to delete color input fields

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#4]
**Describe the solution you'd like**
A small close button in the top right corner of each input field that deletes it. This may require moving the circular color swatch slightly to accommodate the button

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by Hat52** [comment]
**My approach to this problem**
We can create a delete icon button on the top right corner of the text field. And if the user click that button we will simply remove that index from our color array

**Comment by EmmaDawsonDev** [comment]
> **My approach to this problem** We can create a delete icon button on the top right corner of the text field. And if the user click that button we will simply remove that index from our color array

Sounds good, that's how I was thinking to approach it too. I've installed react icons in the project so you can add the icon from there.

However, it should probably not be possible to delete the first 2 inputs.

**Comment by Hat52** [comment]
Okay thanks for clarifying.
