### ISSUE TITLE
Add reset all button

### ISSUE THREAD

**Issue by EmmaDawsonDev** [AccessibleForAll/ColorPaletteCombos#5]
It would be good if there were a reset button which resets the color inputs back to their original state

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by Hat52** [comment]
- Should the reset button be next to the add color button?
- What happen if the user added a new color field and then hit the reset button, do we need to remove the added field and rest the field to only two field?

**Comment by EmmaDawsonDev** [comment]
Yes, the reset button should be next to the add button. It should probably be the grey colour instead of the black though. currently I just styled it on the button element in the index.css file as I only had one button but you should give a class to each button and add the background colour/ text colour there instead.

when resetting all, I want all the extra input fields to be removed and returned back to the two original with black and white.

Any more questions, please let me know 😊

**Comment by Hat52** [comment]
thanks everything is clear for now :)

**Comment by EmmaDawsonDev** [comment]
Closed by https://github.com/AccessibleForAll/ColorPaletteCombos/commit/a3639d53a0140a283dd0aa4721628a9b5343f18a
